# Generated by Django 3.1.4 on 2021-01-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20201229_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blogcontent')),
                ('blog_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blogtag')),
            ],
        ),
    ]
